background {
    monitor =
    path = /home/nexus/.local/share/wallpapers/trippy-purple.png
    blur_passes = 2
    contrast   = 0.9
    brightness = 0.8
    vibrancy   = 0.2
}

# Clock
label {
    monitor =
    text      = cmd[update:1000] echo "$(date +"%H:%M")"
    color     = rgba(224, 222, 244, 1.0)
    font_size   = 72
    font_family = JetBrains Mono Bold
    position  = 0, 80
    halign    = center
    valign    = center
}

# Date
label {
    monitor =
    text      = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color     = rgba(224, 222, 244, 0.8)
    font_size   = 18
    font_family = JetBrains Mono
    position  = 0, 10
    halign    = center
    valign    = center
}

# Input field
input-field {
    monitor =
    size             = 300, 50
    outline_thickness = 2
    dots_size        = 0.25
    dots_spacing     = 0.2
    dots_center      = true
    outer_color      = rgba(235, 111, 146, 0.8)
    inner_color      = rgba(25, 23, 36, 0.8)
    font_color       = rgba(224, 222, 244, 1.0)
    fade_on_empty    = true
    font_family      = JetBrains Mono
    placeholder_text = <i>password</i>
    hide_input       = false
    rounding         = 8
    position         = 0, -60
    halign           = center
    valign           = center
    check_color      = rgba(196, 167, 231, 1.0)
    fail_color       = rgba(235, 111, 146, 1.0)
    fail_text        = <i>$FAIL ($ATTEMPTS)</i>
}
